#!/usr/bin/env python
import sys
if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
        print "yes"
elif len(sys.argv) == 2 and sys.argv[1] == "config":
        print 'graph_title IPVS Packets'
        print 'graph_vlabel pps'
        print 'graph_category ipvs'
        print 'graph_order packetsin packetsout'
        print 'packetsin.label Packets IN'
        print 'packetsin.type DERIVE'
        print 'packetsout.label Packets OUT'
        print 'packetsout.type DERIVE'
        print 'graph_args --base 1000'
else:
        readfile = open('/proc/net/ip_vs_stats', 'r')
        i = 0
        for line in readfile:
                i = i + 1
                if i == 3:
                        conns, packetsin, packetsout, bytesin, bytesout = line.split()
                        print("packetsin.value " + str(int(packetsin, 16)))
                        print("packetsout.value " + str(int(packetsout, 16)))

